SFR-1533: Include selected languages in filters
NYPL/sfr-bookfinder-front-end pull request #354
Opened 2022-10-03 18:33 UTC by jackiequach

[Jira Ticket](http://jira.nypl.org/browse/SFR-1533)

### This PR does the following:
- Add selected languages to the available options when there are no results for the selected languages

### Testing requirements & instructions: 
-

2022-10-06 13:59 UTC, hokei requested changes
As this is an edge case that I imagine we're not going to check every time, we should have a test for this.  

Also - and this is a style/implementation thing - as we've recently added a new filter type, have you considered an implementation that first loads all of the selected filters, and then adds in all of the available options from data (instead of this implementation, which first looks at the filter-able options in the data and then adds the selected stuff if they're not already in there).  

I'm thinking about this because, in this implementation, if we wanted to add any new filter times we would have to first remember that this bug is possible with that new filter, and remember to specifically handle it if it is.  Whereas, if we handle all the applied filters up front, we don't need to worry about if it's a "disappearing" filter or not.

2022-10-07 17:27 UTC, jackiequach commented
I think it would be good to implement a Playwright test for this particular edge case since it would be an E2E test utilizing both frontend and backend data. 

I see what you mean for loading the selected filters first, but since we get count for each language from the backend, the selected filter would need to be replaced with the available option to populate the count. We would still need to check if it's a "disappearing" filter.

@hokei Please let me know your thoughts on this and if I am misunderstanding any of it.

2022-10-12 19:34 UTC, hokei requested changes
That makes sense, re: the progressive filters.  

For the test, recapping what we talked about in our 1:1 -- try adding a mock for the fetch request and making it return the minimal fixture that would have caused this erroneous behavior.  Then you can assert that this behavior doesn't happen.  In general we don't want to use E2E tests for edge cases because they're still pretty expensive to execute.

2022-10-13 21:23 UTC, hokei approved these changes

2022-10-17 14:17 UTC, merged